#!/bin/bash

rm main_cpu
make main_cpu
./main_cpu	../../../data/bfs/graph65536.txt >> output/bfs/CPU/graph65536_1.log
./main_cpu	../../../data/bfs/graph65536.txt >> output/bfs/CPU/graph65536_2.log
./main_cpu	../../../data/bfs/graph65536.txt >> output/bfs/CPU/graph65536_3.log
./main_cpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/CPU/graph1MW_6_1.log
./main_cpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/CPU/graph1MW_6_2.log
./main_cpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/CPU/graph1MW_6_3.log

#!/bin/bash
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=1"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_1.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_2.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_3.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_1.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_2.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_3.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=2"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_1.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_2.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_3.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_1.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_2.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_3.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=4"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_1.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_2.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_3.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_1.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_2.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_3.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=8"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_1.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_2.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_3.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_1.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_2.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_3.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=16"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_1.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_2.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_3.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_1.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_2.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_3.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=32"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_1.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_2.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_3.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_1.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_2.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_3.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=64"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_1.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_2.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_3.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_1.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_2.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_3.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=128"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_1.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_2.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_3.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_1.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_2.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_3.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=512"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_1.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_2.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_3.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_1.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_2.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_3.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=1024"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_1.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_2.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_3.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_1.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_2.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_3.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=2048"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_1.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_2.log
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/graph65536_3.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_1.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_2.log
./main_gpu	../../../data/bfs/graph1MW_6.txt >> output/bfs/GPU/graph1MW_6_3.log
					
#!/bin/bash
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=1"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/test.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=2"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/test.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=4"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/test.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=8"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/test.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=16"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/test.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=32"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/test.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=64"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/test.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=128"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/test.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=512"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/test.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=1024"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/test.log
rm bfs_gpu
make bfs_gpu PARA="WORK_GROUP=2048"
./main_gpu	../../../data/bfs/graph65536.txt >> output/bfs/GPU/test.log
